# Generated by Django 3.1.7 on 2021-05-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210502_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_phone',
            new_name='mobilephone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_pass',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
