# Generated by Django 3.1.7 on 2021-05-03 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210502_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whiteips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whiteips', models.CharField(max_length=128, unique=True, verbose_name='可信IP')),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
