# Generated by Django 3.1.7 on 2021-05-03 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_whiteips'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Whiteips',
            new_name='Whiteip',
        ),
        migrations.RenameField(
            model_name='whiteip',
            old_name='whiteips',
            new_name='whiteip',
        ),
    ]
