# Generated by Django 4.0 on 2022-01-15 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_options_account_today_cost'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='name',
        ),
        migrations.AddField(
            model_name='contract',
            name='company_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='公司名称'),
            preserve_default=False,
        ),
    ]
