# Generated by Django 4.0 on 2022-01-18 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_created_at_account_updated_at'),
        ('contracts', '0004_alter_contract_company_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='company_name',
        ),
        migrations.AddField(
            model_name='contract',
            name='company_address',
            field=models.CharField(max_length=40, null=True, verbose_name='公司地址'),
        ),
        migrations.AddField(
            model_name='contract',
            name='company_license_doc',
            field=models.FileField(blank=True, null=True, upload_to='contracts/company_license/', verbose_name='营业执照'),
        ),
        migrations.AddField(
            model_name='contract',
            name='company_owner_doc',
            field=models.FileField(blank=True, null=True, upload_to='contracts/person/', verbose_name='法人证件'),
        ),
        migrations.AddField(
            model_name='contract',
            name='company_title',
            field=models.CharField(max_length=40, null=True, verbose_name='公司名称'),
        ),
        migrations.AddField(
            model_name='contract',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='关联账户'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='company_license',
            field=models.CharField(max_length=20, null=True, verbose_name='税号'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='company_owner',
            field=models.CharField(max_length=10, null=True, verbose_name='法人'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_doc',
            field=models.FileField(blank=True, null=True, upload_to='contracts/contract_doc/', verbose_name='合同附件'),
        ),
    ]
