# Generated by Django 4.0 on 2022-01-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_remove_contract_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_contract_ok',
            field=models.BooleanField(default=False, verbose_name='合同签署？'),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_license_ok',
            field=models.BooleanField(default=False, verbose_name='证照齐全？'),
        ),
    ]
