# Generated by Django 4.0 on 2022-01-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_account_options_account_today_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=1000, null=True, verbose_name='话术内容')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='words/', verbose_name='附件')),
                ('is_approved', models.BooleanField(default=False, verbose_name='是否审核通过')),
                ('huashu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='话术')),
            ],
        ),
    ]
