# Generated by Django 4.0 on 2022-01-16 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name_plural': '话术报备'},
        ),
    ]
