# Generated by Django 4.0 on 2022-01-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_alter_word_huashu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='huashu',
            new_name='user_name',
        ),
    ]
