# Generated by Django 4.0 on 2022-01-18 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_created_at_account_updated_at'),
        ('words', '0005_rename_huashu_word_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_name', models.CharField(max_length=30, unique=True, verbose_name='网关名称')),
                ('gateway_type', models.CharField(choices=[('DJWG', '对接网关'), ('LDWG', '落地网关')], max_length=40, verbose_name='网关类型')),
                ('huashu', models.ManyToManyField(to='words.Word')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='关联用户')),
            ],
            options={
                'verbose_name_plural': '网关管理',
            },
        ),
    ]
