# Generated by Django 4.0 on 2022-01-18 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0009_alter_gateway_huashu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_name', models.CharField(max_length=10, verbose_name='前缀')),
                ('related_gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.gateway', verbose_name='关联网关')),
            ],
        ),
    ]
