# Generated by Django 4.0 on 2022-01-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0010_prefix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prefix',
            options={'verbose_name_plural': '前缀管理'},
        ),
        migrations.AddField(
            model_name='prefix',
            name='callee_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='主叫号码'),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='prefix_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='被叫前缀'),
        ),
    ]
