# Generated by Django 4.0 on 2022-01-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name_plural': '账户信息'},
        ),
        migrations.AddField(
            model_name='account',
            name='today_cost',
            field=models.FloatField(default=20, verbose_name='今日消费'),
            preserve_default=False,
        ),
    ]
