# Generated by Django 4.0 on 2022-01-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_options_account_today_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='kh_type',
            field=models.CharField(choices=[('PTZH', '普通账户'), ('JSZH', '结算账户')], default='PTZH', max_length=20, verbose_name='账户类型'),
            preserve_default=False,
        ),
    ]
