# Generated by Django 4.0 on 2022-02-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_created_at_account_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(blank=True, null=True, verbose_name='账户余额'),
        ),
        migrations.AlterField(
            model_name='account',
            name='credit_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='透支额度'),
        ),
        migrations.AlterField(
            model_name='account',
            name='today_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='今日消费'),
        ),
    ]
