# Generated by Django 4.0 on 2022-02-24 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_balance_alter_account_credit_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='credit_amount',
        ),
        migrations.RemoveField(
            model_name='account',
            name='today_cost',
        ),
    ]
